import { SYMBOL_UNIVERSE } from "./symbols";
import { priceFeed, SnapshotData } from "./priceFeed";

/**
 * ============================================================================
 * SYNTHETIC DEMO-CONTINUITY DATA NOTICE:
 * The return series generated by seedCorrelationHistory() are synthetic
 * mock data used specifically to solve the cold-start problem for Pearson
 * correlation (rho) and beta calculations upon server boot.
 *
 * This is NOT real historical market data and must NEVER be treated as an
 * official or production data feed. It guarantees that the correlation/beta
 * engine has sufficient overlapping data points (5+) so sector contagion
 * signals fire reliably during product demonstrations.
 * ============================================================================
 */

// Ring buffer capacity for rolling returns
const MAX_RETURN_POINTS = 60;

// Seeded PRNG: Mulberry32 for deterministic, reproducible numbers across restarts
export function createMulberry32(seed: number = 0x1337c0de) {
  let s = seed >>> 0;
  return function next(): number {
    let t = (s += 0x6d2b79f5);
    t = Math.imul(t ^ (t >>> 15), t | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

// Global in-memory storage for rolling return histories
export const stockReturnsHistory: Map<string, number[]> = new Map();
export const sectorReturnsHistory: Map<string, number[]> = new Map();

// Helper to track last known LTP for computing live returns per symbol
const lastKnownPrices: Map<string, number> = new Map();

let isListenerRegistered = false;

/**
 * Seeds ~60 synthetic return points per symbol in SYMBOL_UNIVERSE and
 * per sector factor series with realistic factor-copula correlation structure.
 */
export function seedCorrelationHistory(): void {
  const prng = createMulberry32(0x1337c0de);

  // Collect unique sectors
  const sectors = [...new Set(SYMBOL_UNIVERSE.map(s => s.sector))];

  // 1. Generate one shared market-wide factor return series across 60 time steps.
  // Standard normal approximation via Box-Muller using PRNG
  const marketFactor: number[] = [];
  for (let t = 0; t < MAX_RETURN_POINTS; t++) {
    const u1 = Math.max(1e-6, prng());
    const u2 = prng();
    const z = Math.sqrt(-2.0 * Math.log(u1)) * Math.cos(2.0 * Math.PI * u2);
    // Typical market daily return standard deviation ~ 0.8%
    marketFactor.push(z * 0.008);
  }

  // 2. Generate one shared sector-factor return series per sector
  // Sector factor = 0.15 * marketFactor + 0.85 * sectorInnovation
  sectors.forEach(sector => {
    const sectorSeries: number[] = [];
    for (let t = 0; t < MAX_RETURN_POINTS; t++) {
      const u1 = Math.max(1e-6, prng());
      const u2 = prng();
      const z = Math.sqrt(-2.0 * Math.log(u1)) * Math.cos(2.0 * Math.PI * u2);
      const sectorInnovation = z * 0.012; // Sector volatility ~ 1.2%
      const factorReturn = 0.15 * marketFactor[t] + 0.85 * sectorInnovation;
      sectorSeries.push(Number(factorReturn.toFixed(5)));
    }
    sectorReturnsHistory.set(sector, sectorSeries);
  });

  // 3. For each stock in SYMBOL_UNIVERSE, assign a beta between 0.7 and 1.4
  // return_i = sector_factor * beta_i + idiosyncratic_noise
  SYMBOL_UNIVERSE.forEach(stock => {
    const sectorFactor = sectorReturnsHistory.get(stock.sector) || [];
    // Randomized beta between 0.70 and 1.40
    const beta = 0.7 + prng() * 0.7;

    const stockSeries: number[] = [];
    for (let t = 0; t < MAX_RETURN_POINTS; t++) {
      const u1 = Math.max(1e-6, prng());
      const u2 = prng();
      const z = Math.sqrt(-2.0 * Math.log(u1)) * Math.cos(2.0 * Math.PI * u2);
      const idiosyncratic = z * 0.006; // Idiosyncratic noise ~ 0.6%
      const stockReturn = (sectorFactor[t] || 0) * beta + idiosyncratic;
      stockSeries.push(Number(stockReturn.toFixed(5)));
    }

    stockReturnsHistory.set(stock.symbol, stockSeries);
    lastKnownPrices.set(stock.symbol, stock.basePrice);
  });

  console.log(
    `[CorrelationSeeder] Seeded ${stockReturnsHistory.size} symbols and ${sectorReturnsHistory.size} sectors with ${MAX_RETURN_POINTS} historical return points.`
  );

  // Register tick listener once to extend seeded buffers seamlessly during live execution
  if (!isListenerRegistered) {
    priceFeed.onTick((snap: SnapshotData) => {
      appendLiveTick(snap);
    });
    isListenerRegistered = true;
  }
}

/**
 * Extends the return series with live tick data without resetting seeded base.
 */
export function appendLiveTick(snap: SnapshotData): void {
  const prevPrice = lastKnownPrices.get(snap.symbol);
  if (prevPrice !== undefined && prevPrice > 0) {
    const returnDelta = (snap.ltp - prevPrice) / prevPrice;
    const history = stockReturnsHistory.get(snap.symbol) || [];
    history.push(Number(returnDelta.toFixed(5)));
    if (history.length > MAX_RETURN_POINTS) {
      history.shift();
    }
    stockReturnsHistory.set(snap.symbol, history);
  }
  lastKnownPrices.set(snap.symbol, snap.ltp);

  // Also maintain sector returns ring buffer
  const symbolInfo = SYMBOL_UNIVERSE.find(s => s.symbol === snap.symbol);
  if (symbolInfo) {
    const sector = symbolInfo.sector;
    const sectorPct = priceFeed.getSectorChangePct(sector);
    const sectorReturn = sectorPct / 100;
    const sectorHistory = sectorReturnsHistory.get(sector) || [];
    sectorHistory.push(Number(sectorReturn.toFixed(5)));
    if (sectorHistory.length > MAX_RETURN_POINTS) {
      sectorHistory.shift();
    }
    sectorReturnsHistory.set(sector, sectorHistory);
  }
}

export function getStockReturns(symbol: string): number[] {
  return stockReturnsHistory.get(symbol) || [];
}

export function getSectorReturns(sector: string): number[] {
  return sectorReturnsHistory.get(sector) || [];
}
